package com.identifyocr.model.enums

enum class CropType {
    FULL_ID_CARD,MRZ_AREA,BARCODE_AREA,FACE,DATE_OF_BIRTH,DOCUMENT_NO,VALID_UNTIL,ID_NUMBER,INFO_AREA,PASSPORT_NO, NAME, SURNAME, GENDER, NATIONALITY,
    MOTHER_NAME, FATHER_NAME, ISSUED_BY
}
