package com.identifyocr.model.enums

enum class IdentifyInformationTypes {
    AGENT_CALL_INFORMATION,
    SPEECH_TEST_INFORMATION,
    ID_CARD_NFC_INFORMATION,
    PASSPORT_NFC_INFORMATION,
    LIVENESS_INFORMATION,
    LIVENESS_SMILE_INFORMATION,
    LIVENESS_BLINK_INFORMATION,
    LIVENESS_TURN_RIGHT_INFORMATION,
    LIVENESS_TURN_LEFT_INFORMATION,
    SCAN_FRONT_OF_CARD_INFORMATION,
    SCAN_BACK_OF_CARD_INFORMATION,
    SCAN_PASSPORT_INFORMATION,
    TAKE_SELFIE_INFORMATION,
    VIDEO_RECORD_INFORMATION,
    SIGNATURE_INFORMATION,
    VALIDATE_ADDRESS_INFORMATION,
    TAKE_PHOTO_FRONT_OF_OTHER_CARD_INFORMATION,
    TAKE_PHOTO_BACK_OF_OTHER_CARD_INFORMATION
}
